// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'parkingData.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ParkingData _$ParkingDataFromJson(Map<String, dynamic> json) {
  return ParkingData(
    addRates: (json['ADD_RATES'] as num?)?.toDouble(),
    addTimeRate: (json['ADD_TIME_RATE'] as num?)?.toDouble(),
    addr: json['ADDR'] as String?,
    assignCode: json['ASSIGN_CODE'] as String?,
    assignCodeName: json['ASSIGN_CODE_NM'] as String?,
    busAddRates: (json['BUS_ADD_RATES'] as num?)?.toDouble(),
    busAddTimeRate: (json['BUS_ADD_TIME_RATE'] as num?)?.toDouble(),
    busRates: (json['BUS_RATES'] as num?)?.toDouble(),
    busTimeRate: (json['BUS_TIME_RATE'] as num?)?.toDouble(),
    capacity: (json['CAPACITY'] as num?)?.toDouble(),
    dayMaximum: (json['DAY_MAXIMUM'] as num?)?.toDouble(),
    fulltimeMonthly: json['FULLTIME_MONTHLY'] as String?,
    grpParkName: json['GRP_PARKNM'] as String?,
    holidayBeginTime: json['HOLIDAY_BEGIN_TIME'] as String?,
    holidayEndTime: json['HOLIDAY_END_TIME'] as String?,
    holidayPayName: json['HOLIDAY_PAY_NM'] as String?,
    holidayPayYn: json['HOLIDAY_PAY_YN'] as String?,
    lat: (json['LAT'] as num?)?.toDouble(),
    lng: (json['LNG'] as num?)?.toDouble(),
    nightFreeOpen: json['NIGHT_FREE_OPEN'] as String?,
    nightFreeOpenName: json['NIGHT_FREE_OPEN_NM'] as String?,
    operationRule: json['OPERATION_RULE'] as String?,
    operationRuleName: json['OPERATION_RULE_NM'] as String?,
    parkingCode: json['PARKING_CODE'] as String?,
    parkingName: json['PARKING_NAME'] as String?,
    parkingType: json['PARKING_TYPE'] as String?,
    parkingTypeName: json['PARKING_TYPE_NM'] as String?,
    payYn: json['PAY_YN'] as String?,
    payYnName: json['PAY_NM'] as String?,
    ratest: (json['RATES'] as num?)?.toDouble(),
    saturDayPayName: json['SATURDAY_PAY_NM'] as String?,
    saturDayPayYn: json['SATURDAY_PAY_YN'] as String?,
    syncTime: json['SYNC_TIME'] as String?,
    tel: json['TEL'] as String?,
    timeRate: (json['TIME_RATE'] as num?)?.toDouble(),
    weekDayBeginTime: json['WEEKDAY_BEGIN_TIME'] as String?,
    weekDayEndTime: json['WEEKDAY_END_TIME'] as String?,
    weekEndBeginTime: json['WEEKEND_BEGIN_TIME'] as String?,
    weekEndEndTime: json['WEEKEND_END_TIME'] as String?,
  );
}

Map<String, dynamic> _$ParkingDataToJson(ParkingData instance) =>
    <String, dynamic>{
      'PARKING_NAME': instance.parkingName,
      'ADDR': instance.addr,
      'PARKING_CODE': instance.parkingCode,
      'PARKING_TYPE': instance.parkingType,
      'PARKING_TYPE_NM': instance.parkingTypeName,
      'OPERATION_RULE': instance.operationRule,
      'OPERATION_RULE_NM': instance.operationRuleName,
      'TEL': instance.tel,
      'CAPACITY': instance.capacity,
      'PAY_YN': instance.payYn,
      'PAY_NM': instance.payYnName,
      'NIGHT_FREE_OPEN': instance.nightFreeOpen,
      'NIGHT_FREE_OPEN_NM': instance.nightFreeOpenName,
      'WEEKDAY_BEGIN_TIME': instance.weekDayBeginTime,
      'WEEKDAY_END_TIME': instance.weekDayEndTime,
      'WEEKEND_BEGIN_TIME': instance.weekEndBeginTime,
      'WEEKEND_END_TIME': instance.weekEndEndTime,
      'HOLIDAY_BEGIN_TIME': instance.holidayBeginTime,
      'HOLIDAY_END_TIME': instance.holidayEndTime,
      'SYNC_TIME': instance.syncTime,
      'SATURDAY_PAY_YN': instance.saturDayPayYn,
      'SATURDAY_PAY_NM': instance.saturDayPayName,
      'HOLIDAY_PAY_YN': instance.holidayPayYn,
      'HOLIDAY_PAY_NM': instance.holidayPayName,
      'FULLTIME_MONTHLY': instance.fulltimeMonthly,
      'GRP_PARKNM': instance.grpParkName,
      'RATES': instance.ratest,
      'TIME_RATE': instance.timeRate,
      'ADD_RATES': instance.addRates,
      'ADD_TIME_RATE': instance.addTimeRate,
      'BUS_RATES': instance.busRates,
      'BUS_TIME_RATE': instance.busTimeRate,
      'BUS_ADD_TIME_RATE': instance.busAddTimeRate,
      'BUS_ADD_RATES': instance.busAddRates,
      'DAY_MAXIMUM': instance.dayMaximum,
      'LAT': instance.lat,
      'LNG': instance.lng,
      'ASSIGN_CODE': instance.assignCode,
      'ASSIGN_CODE_NM': instance.assignCodeName,
    };
